### ISSUE TITLE
jemalloc

### ISSUE THREAD

**Issue by Venorcis** [iusrepo/redis5#1]
I was wondering why the bundled custom jemalloc is (purposely) not used in this build, as is the default on Redis builds from source? This prevents features like active defrag from working.

**Comment by carlwgeorge** [comment]
IUS forks our spec files from Fedora.  Fedora's policy is to [use system libraries whenever possible](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling), so we have inherited that choice.  Reading through the [redis deps readme file](https://github.com/antirez/redis/blob/5.0/deps/README.md#jemalloc), I can see that they have customized jemalloc for the active defragmentation logic.  Redis does specifically support using the customized bundled jemalloc or another jemalloc (such as the system library).  They describe that feature as not mandatory, which is probably why Fedora made the choice they did.

Customized bundled libraries are a common reason in Fedora to use the bundled library.  IUS normally prefers to only diverge from Fedora choices when necessary.  If you open this same request for the Fedora package, and are able to convince them, we'll definitely port the change to the IUS package.  If Fedora declines, IUS will have to decide if the change is important enough to diverge from Fedora's choice.

https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=redis

**Comment by Venorcis** [comment]
Thanks for the info @carlwgeorge
I've submitted a request https://bugzilla.redhat.com/show_bug.cgi?id=1725852

**Comment by carlwgeorge** [comment]
This has been fixed in the Fedora package, and I've cherry-picked the [relevant commit](https://src.fedoraproject.org/rpms/redis/c/244dcfee3638e1b219ec577508481ade1154fd7b) to the IUS package.  redis5-5.0.5-2 is now available in ius-testing.  Try it out and let me know if that works for you.

**Comment by Venorcis** [comment]
> This has been fixed in the Fedora package, and I've cherry-picked the [relevant commit](https://src.fedoraproject.org/rpms/redis/c/244dcfee3638e1b219ec577508481ade1154fd7b) to the IUS package. redis5-5.0.5-2 is now available in ius-testing. Try it out and let me know if that works for you.

I've just tested this and active-defrag indeed activates successfully with that build :)

**Comment by carlwgeorge** [comment]
Awesome, thanks @Venorcis.  I've promoted that build from testing.  Thanks for reporting this to IUS and to Fedora to improve the packages.
