### ISSUE TITLE
redis5 packages are missing from repository

### ISSUE THREAD

**Issue by gtirloni** [iusrepo/redis5#5]
```
$ repoquery --disablerepo='*' --enablerepo=ius -qa | grep redis
php74-pecl-redis-0:5.2.2-1.el7.ius.x86_64
python36-redis-0:2.10.6-2.el7.ius.noarch
redis6-0:6.2.7-3.el7.ius.x86_64
redis6-devel-0:6.2.7-3.el7.ius.x86_64
redis6-doc-0:6.2.7-3.el7.ius.noarch
```

Were they deleted?

**Comment by carlwgeorge** [comment]
Redis 5 is EOL upstream, so it was moved to the archive repo.  You can still install it from there but it will no longer be maintained (no updates, no security fixes).  This was announced [here](https://github.com/iusrepo/announce/issues/37).  If you use IUS packages I suggest subscribing to that repo to be notified of package retirements.
